// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderHub.Infrastructure.Persistence;

#nullable disable

namespace OrderHub.Infrastructure.Migrations
{
    [DbContext(typeof(OrderProcessorContext))]
    partial class OrderProcessorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderHub.DAL.Domain.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Embroidery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Embroidery = "alaa",
                            Quantity = 10L,
                            Sku = "SKU001"
                        },
                        new
                        {
                            Id = 2,
                            Embroidery = "star",
                            Quantity = 20L,
                            Sku = "SKU002"
                        },
                        new
                        {
                            Id = 3,
                            Embroidery = "a",
                            Quantity = 30L,
                            Sku = "SKU003"
                        });
                });

            modelBuilder.Entity("OrderHub.DAL.Domain.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TierCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "School Silver",
                            TierCode = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "School Gold",
                            TierCode = 2
                        });
                });

            modelBuilder.Entity("OrderHub.DAL.Domain.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 100,
                            Sku = "SKU001"
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 200,
                            Sku = "SKU002"
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 300,
                            Sku = "SKU003"
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderLineId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("StockId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 10.00m,
                            Name = "Product 1",
                            Sku = "SKU001",
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 15.00m,
                            Name = "Product 2",
                            Sku = "SKU002",
                            StockId = 2
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 20.00m,
                            Name = "Product 3",
                            Sku = "SKU003",
                            StockId = 3
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Models.Product", b =>
                {
                    b.HasOne("OrderHub.DAL.Domain.Models.OrderLine", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderLineId");

                    b.HasOne("OrderHub.DAL.Domain.Models.Stock", "Stock")
                        .WithMany("Products")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("OrderHub.DAL.Domain.Models.OrderLine", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OrderHub.DAL.Domain.Models.Stock", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
